name: pa_partner
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
    
  common:
    path: ../common

  core:
    path: ../core


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.7
  country_code_picker: ^3.0.0
  go_router: ^13.2.2
  meta: ^1.11.0
  custom_date_range_picker: ^1.0.10
  chips_choice:  
  flutter_svg: ^2.0.10+1
  time_planner:
    git: 
      url: https://github.com/shceo/time_planner.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter


  dart_code_metrics_presets: ^2.10.0
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    # - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
